[programs.localnet]
video_storage = "Dpq6qaHAnKd1Pqf2fD6P9prcgmMasazTYvryjtAdb87x"

[provider]
cluster = "localnet"
wallet = "C:\\Users\\user\\.config\\solana\\id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
resolution = true
skip-lint = false


